// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: protobufs/user_balance.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create user balance entry in db
type CreateUserBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserBalanceRequest) Reset() {
	*x = CreateUserBalanceRequest{}
	mi := &file_protobufs_user_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserBalanceRequest) ProtoMessage() {}

func (x *CreateUserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_user_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserBalanceRequest.ProtoReflect.Descriptor instead.
func (*CreateUserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_user_balance_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserBalanceRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateUserBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserBalanceResponse) Reset() {
	*x = CreateUserBalanceResponse{}
	mi := &file_protobufs_user_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserBalanceResponse) ProtoMessage() {}

func (x *CreateUserBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_user_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserBalanceResponse.ProtoReflect.Descriptor instead.
func (*CreateUserBalanceResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_user_balance_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Get user's current balance(available & locked)
type GetUserBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBalanceRequest) Reset() {
	*x = GetUserBalanceRequest{}
	mi := &file_protobufs_user_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceRequest) ProtoMessage() {}

func (x *GetUserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_user_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetUserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_user_balance_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserBalanceRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserBalanceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AvailableBalance int64                  `protobuf:"varint,1,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	LockedBalance    int64                  `protobuf:"varint,2,opt,name=locked_balance,json=lockedBalance,proto3" json:"locked_balance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserBalanceResponse) Reset() {
	*x = GetUserBalanceResponse{}
	mi := &file_protobufs_user_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBalanceResponse) ProtoMessage() {}

func (x *GetUserBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_user_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetUserBalanceResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_user_balance_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserBalanceResponse) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *GetUserBalanceResponse) GetLockedBalance() int64 {
	if x != nil {
		return x.LockedBalance
	}
	return 0
}

// Increase user's available balance
type IncreaseUserBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseUserBalanceRequest) Reset() {
	*x = IncreaseUserBalanceRequest{}
	mi := &file_protobufs_user_balance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseUserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseUserBalanceRequest) ProtoMessage() {}

func (x *IncreaseUserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_user_balance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseUserBalanceRequest.ProtoReflect.Descriptor instead.
func (*IncreaseUserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_user_balance_proto_rawDescGZIP(), []int{4}
}

func (x *IncreaseUserBalanceRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IncreaseUserBalanceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type IncreaseUserBalanceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UpdatedBalance int64                  `protobuf:"varint,1,opt,name=updated_balance,json=updatedBalance,proto3" json:"updated_balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IncreaseUserBalanceResponse) Reset() {
	*x = IncreaseUserBalanceResponse{}
	mi := &file_protobufs_user_balance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseUserBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseUserBalanceResponse) ProtoMessage() {}

func (x *IncreaseUserBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_user_balance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseUserBalanceResponse.ProtoReflect.Descriptor instead.
func (*IncreaseUserBalanceResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_user_balance_proto_rawDescGZIP(), []int{5}
}

func (x *IncreaseUserBalanceResponse) GetUpdatedBalance() int64 {
	if x != nil {
		return x.UpdatedBalance
	}
	return 0
}

// Lock user's available balance
type LockUserBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockUserBalanceRequest) Reset() {
	*x = LockUserBalanceRequest{}
	mi := &file_protobufs_user_balance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockUserBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockUserBalanceRequest) ProtoMessage() {}

func (x *LockUserBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_user_balance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockUserBalanceRequest.ProtoReflect.Descriptor instead.
func (*LockUserBalanceRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_user_balance_proto_rawDescGZIP(), []int{6}
}

func (x *LockUserBalanceRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LockUserBalanceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type LockUserBalanceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AvailableBalance int64                  `protobuf:"varint,1,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	LockedBalance    int64                  `protobuf:"varint,2,opt,name=locked_balance,json=lockedBalance,proto3" json:"locked_balance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LockUserBalanceResponse) Reset() {
	*x = LockUserBalanceResponse{}
	mi := &file_protobufs_user_balance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockUserBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockUserBalanceResponse) ProtoMessage() {}

func (x *LockUserBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_user_balance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockUserBalanceResponse.ProtoReflect.Descriptor instead.
func (*LockUserBalanceResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_user_balance_proto_rawDescGZIP(), []int{7}
}

func (x *LockUserBalanceResponse) GetAvailableBalance() int64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *LockUserBalanceResponse) GetLockedBalance() int64 {
	if x != nil {
		return x.LockedBalance
	}
	return 0
}

var File_protobufs_user_balance_proto protoreflect.FileDescriptor

const file_protobufs_user_balance_proto_rawDesc = "" +
	"\n" +
	"\x1cprotobufs/user_balance.proto\x12\tprotobufs\"3\n" +
	"\x18CreateUserBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"5\n" +
	"\x19CreateUserBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x15GetUserBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"l\n" +
	"\x16GetUserBalanceResponse\x12+\n" +
	"\x11available_balance\x18\x01 \x01(\x03R\x10availableBalance\x12%\n" +
	"\x0elocked_balance\x18\x02 \x01(\x03R\rlockedBalance\"M\n" +
	"\x1aIncreaseUserBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"F\n" +
	"\x1bIncreaseUserBalanceResponse\x12'\n" +
	"\x0fupdated_balance\x18\x01 \x01(\x03R\x0eupdatedBalance\"I\n" +
	"\x16LockUserBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"m\n" +
	"\x17LockUserBalanceResponse\x12+\n" +
	"\x11available_balance\x18\x01 \x01(\x03R\x10availableBalance\x12%\n" +
	"\x0elocked_balance\x18\x02 \x01(\x03R\rlockedBalance2\x93\x03\n" +
	"\x12UserBalanceService\x12`\n" +
	"\x11CreateUserBalance\x12#.protobufs.CreateUserBalanceRequest\x1a$.protobufs.CreateUserBalanceResponse\"\x00\x12W\n" +
	"\x0eGetUserBalance\x12 .protobufs.GetUserBalanceRequest\x1a!.protobufs.GetUserBalanceResponse\"\x00\x12f\n" +
	"\x13IncreaseUserBalance\x12%.protobufs.IncreaseUserBalanceRequest\x1a&.protobufs.IncreaseUserBalanceResponse\"\x00\x12Z\n" +
	"\x0fLockUserBalance\x12!.protobufs.LockUserBalanceRequest\x1a\".protobufs.LockUserBalanceResponse\"\x00B1Z/github.com/Sam-Frost/accounts-service/protobufsb\x06proto3"

var (
	file_protobufs_user_balance_proto_rawDescOnce sync.Once
	file_protobufs_user_balance_proto_rawDescData []byte
)

func file_protobufs_user_balance_proto_rawDescGZIP() []byte {
	file_protobufs_user_balance_proto_rawDescOnce.Do(func() {
		file_protobufs_user_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobufs_user_balance_proto_rawDesc), len(file_protobufs_user_balance_proto_rawDesc)))
	})
	return file_protobufs_user_balance_proto_rawDescData
}

var file_protobufs_user_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protobufs_user_balance_proto_goTypes = []any{
	(*CreateUserBalanceRequest)(nil),    // 0: protobufs.CreateUserBalanceRequest
	(*CreateUserBalanceResponse)(nil),   // 1: protobufs.CreateUserBalanceResponse
	(*GetUserBalanceRequest)(nil),       // 2: protobufs.GetUserBalanceRequest
	(*GetUserBalanceResponse)(nil),      // 3: protobufs.GetUserBalanceResponse
	(*IncreaseUserBalanceRequest)(nil),  // 4: protobufs.IncreaseUserBalanceRequest
	(*IncreaseUserBalanceResponse)(nil), // 5: protobufs.IncreaseUserBalanceResponse
	(*LockUserBalanceRequest)(nil),      // 6: protobufs.LockUserBalanceRequest
	(*LockUserBalanceResponse)(nil),     // 7: protobufs.LockUserBalanceResponse
}
var file_protobufs_user_balance_proto_depIdxs = []int32{
	0, // 0: protobufs.UserBalanceService.CreateUserBalance:input_type -> protobufs.CreateUserBalanceRequest
	2, // 1: protobufs.UserBalanceService.GetUserBalance:input_type -> protobufs.GetUserBalanceRequest
	4, // 2: protobufs.UserBalanceService.IncreaseUserBalance:input_type -> protobufs.IncreaseUserBalanceRequest
	6, // 3: protobufs.UserBalanceService.LockUserBalance:input_type -> protobufs.LockUserBalanceRequest
	1, // 4: protobufs.UserBalanceService.CreateUserBalance:output_type -> protobufs.CreateUserBalanceResponse
	3, // 5: protobufs.UserBalanceService.GetUserBalance:output_type -> protobufs.GetUserBalanceResponse
	5, // 6: protobufs.UserBalanceService.IncreaseUserBalance:output_type -> protobufs.IncreaseUserBalanceResponse
	7, // 7: protobufs.UserBalanceService.LockUserBalance:output_type -> protobufs.LockUserBalanceResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobufs_user_balance_proto_init() }
func file_protobufs_user_balance_proto_init() {
	if File_protobufs_user_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobufs_user_balance_proto_rawDesc), len(file_protobufs_user_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufs_user_balance_proto_goTypes,
		DependencyIndexes: file_protobufs_user_balance_proto_depIdxs,
		MessageInfos:      file_protobufs_user_balance_proto_msgTypes,
	}.Build()
	File_protobufs_user_balance_proto = out.File
	file_protobufs_user_balance_proto_goTypes = nil
	file_protobufs_user_balance_proto_depIdxs = nil
}
