// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: protobufs/user_balance.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserBalanceService_CreateUserBalance_FullMethodName   = "/protobufs.UserBalanceService/CreateUserBalance"
	UserBalanceService_GetUserBalance_FullMethodName      = "/protobufs.UserBalanceService/GetUserBalance"
	UserBalanceService_IncreaseUserBalance_FullMethodName = "/protobufs.UserBalanceService/IncreaseUserBalance"
	UserBalanceService_LockUserBalance_FullMethodName     = "/protobufs.UserBalanceService/LockUserBalance"
)

// UserBalanceServiceClient is the client API for UserBalanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserBalanceServiceClient interface {
	CreateUserBalance(ctx context.Context, in *CreateUserBalanceRequest, opts ...grpc.CallOption) (*CreateUserBalanceResponse, error)
	GetUserBalance(ctx context.Context, in *GetUserBalanceRequest, opts ...grpc.CallOption) (*GetUserBalanceResponse, error)
	IncreaseUserBalance(ctx context.Context, in *IncreaseUserBalanceRequest, opts ...grpc.CallOption) (*IncreaseUserBalanceResponse, error)
	LockUserBalance(ctx context.Context, in *LockUserBalanceRequest, opts ...grpc.CallOption) (*LockUserBalanceResponse, error)
}

type userBalanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserBalanceServiceClient(cc grpc.ClientConnInterface) UserBalanceServiceClient {
	return &userBalanceServiceClient{cc}
}

func (c *userBalanceServiceClient) CreateUserBalance(ctx context.Context, in *CreateUserBalanceRequest, opts ...grpc.CallOption) (*CreateUserBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserBalanceResponse)
	err := c.cc.Invoke(ctx, UserBalanceService_CreateUserBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userBalanceServiceClient) GetUserBalance(ctx context.Context, in *GetUserBalanceRequest, opts ...grpc.CallOption) (*GetUserBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserBalanceResponse)
	err := c.cc.Invoke(ctx, UserBalanceService_GetUserBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userBalanceServiceClient) IncreaseUserBalance(ctx context.Context, in *IncreaseUserBalanceRequest, opts ...grpc.CallOption) (*IncreaseUserBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncreaseUserBalanceResponse)
	err := c.cc.Invoke(ctx, UserBalanceService_IncreaseUserBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userBalanceServiceClient) LockUserBalance(ctx context.Context, in *LockUserBalanceRequest, opts ...grpc.CallOption) (*LockUserBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockUserBalanceResponse)
	err := c.cc.Invoke(ctx, UserBalanceService_LockUserBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserBalanceServiceServer is the server API for UserBalanceService service.
// All implementations must embed UnimplementedUserBalanceServiceServer
// for forward compatibility.
type UserBalanceServiceServer interface {
	CreateUserBalance(context.Context, *CreateUserBalanceRequest) (*CreateUserBalanceResponse, error)
	GetUserBalance(context.Context, *GetUserBalanceRequest) (*GetUserBalanceResponse, error)
	IncreaseUserBalance(context.Context, *IncreaseUserBalanceRequest) (*IncreaseUserBalanceResponse, error)
	LockUserBalance(context.Context, *LockUserBalanceRequest) (*LockUserBalanceResponse, error)
	mustEmbedUnimplementedUserBalanceServiceServer()
}

// UnimplementedUserBalanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserBalanceServiceServer struct{}

func (UnimplementedUserBalanceServiceServer) CreateUserBalance(context.Context, *CreateUserBalanceRequest) (*CreateUserBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserBalance not implemented")
}
func (UnimplementedUserBalanceServiceServer) GetUserBalance(context.Context, *GetUserBalanceRequest) (*GetUserBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserBalance not implemented")
}
func (UnimplementedUserBalanceServiceServer) IncreaseUserBalance(context.Context, *IncreaseUserBalanceRequest) (*IncreaseUserBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncreaseUserBalance not implemented")
}
func (UnimplementedUserBalanceServiceServer) LockUserBalance(context.Context, *LockUserBalanceRequest) (*LockUserBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LockUserBalance not implemented")
}
func (UnimplementedUserBalanceServiceServer) mustEmbedUnimplementedUserBalanceServiceServer() {}
func (UnimplementedUserBalanceServiceServer) testEmbeddedByValue()                            {}

// UnsafeUserBalanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserBalanceServiceServer will
// result in compilation errors.
type UnsafeUserBalanceServiceServer interface {
	mustEmbedUnimplementedUserBalanceServiceServer()
}

func RegisterUserBalanceServiceServer(s grpc.ServiceRegistrar, srv UserBalanceServiceServer) {
	// If the following call panics, it indicates UnimplementedUserBalanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserBalanceService_ServiceDesc, srv)
}

func _UserBalanceService_CreateUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserBalanceServiceServer).CreateUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserBalanceService_CreateUserBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserBalanceServiceServer).CreateUserBalance(ctx, req.(*CreateUserBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserBalanceService_GetUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserBalanceServiceServer).GetUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserBalanceService_GetUserBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserBalanceServiceServer).GetUserBalance(ctx, req.(*GetUserBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserBalanceService_IncreaseUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncreaseUserBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserBalanceServiceServer).IncreaseUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserBalanceService_IncreaseUserBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserBalanceServiceServer).IncreaseUserBalance(ctx, req.(*IncreaseUserBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserBalanceService_LockUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockUserBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserBalanceServiceServer).LockUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserBalanceService_LockUserBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserBalanceServiceServer).LockUserBalance(ctx, req.(*LockUserBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserBalanceService_ServiceDesc is the grpc.ServiceDesc for UserBalanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserBalanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobufs.UserBalanceService",
	HandlerType: (*UserBalanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserBalance",
			Handler:    _UserBalanceService_CreateUserBalance_Handler,
		},
		{
			MethodName: "GetUserBalance",
			Handler:    _UserBalanceService_GetUserBalance_Handler,
		},
		{
			MethodName: "IncreaseUserBalance",
			Handler:    _UserBalanceService_IncreaseUserBalance_Handler,
		},
		{
			MethodName: "LockUserBalance",
			Handler:    _UserBalanceService_LockUserBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobufs/user_balance.proto",
}
